### PR TITLE
Add native targets

### PR DESCRIPTION
**Pull request by luca992**
I added all native targets that kassert supports which are:
```
    "linuxX64",
    "macosX64", "macosArm64",
    "iosArm32", "iosArm64", "iosX64", "iosSimulatorArm64",
    "tvosArm64", "tvosX64", "tvosSimulatorArm64",
    "watchosArm32", "watchosArm64", "watchosX86", "watchosX64", 
    "watchosSimulatorArm64",
```

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Thanks and sorry for the very late review. But the build fails for me with:
```

Some Kotlin/Native targets cannot be built on this linux_x64 machine and are disabled:
    * In project ':core':
        * targets 'macosX64', 'macosArm64', 'iosArm32', 'iosArm64', 'iosX64', 'iosSimulatorArm64', 'tvosArm64', 'tvosX64', 'tvosSimulatorArm64', 'watchosArm32', 'watchosArm64', 'watchosX86', 'watchosX64', 'watchosSimulatorArm64' (can be built with one of the hosts: macos_x64, macos_arm64)
    * In project ':extensions':
        * targets 'macosX64', 'macosArm64', 'iosArm32', 'iosArm64', 'iosX64', 'iosSimulatorArm64', 'tvosArm64', 'tvosX64', 'tvosSimulatorArm64', 'watchosArm32', 'watchosArm64', 'watchosX86', 'watchosX64', 'watchosSimulatorArm64' (can be built with one of the hosts: macos_x64, macos_arm64)
To hide this message, add 'kotlin.native.ignoreDisabledTargets=true' to the Gradle properties.
```
could it be this only works on a mac?

**Comment by luca992** [comment]
> Thanks and sorry for the very late review. But the build fails for me with:
> 
> ```
> 
> Some Kotlin/Native targets cannot be built on this linux_x64 machine and are disabled:
>     * In project ':core':
>         * targets 'macosX64', 'macosArm64', 'iosArm32', 'iosArm64', 'iosX64', 'iosSimulatorArm64', 'tvosArm64', 'tvosX64', 'tvosSimulatorArm64', 'watchosArm32', 'watchosArm64', 'watchosX86', 'watchosX64', 'watchosSimulatorArm64' (can be built with one of the hosts: macos_x64, macos_arm64)
>     * In project ':extensions':
>         * targets 'macosX64', 'macosArm64', 'iosArm32', 'iosArm64', 'iosX64', 'iosSimulatorArm64', 'tvosArm64', 'tvosX64', 'tvosSimulatorArm64', 'watchosArm32', 'watchosArm64', 'watchosX86', 'watchosX64', 'watchosSimulatorArm64' (can be built with one of the hosts: macos_x64, macos_arm64)
> To hide this message, add 'kotlin.native.ignoreDisabledTargets=true' to the Gradle properties.
> ```
> 
> could it be this only works on a mac?

You can't build mac binaries without a mac. But that shouldn't cause an error, are you sure that's not a warning?

**Comment by ligi** [comment]
you are correct - was just a warning - thanks!

**Comment by ligi** [comment]
guess this needs some work on workflows so these targets are build on mac workers - unfortuntately I do not really have time to work on this - but would merge PRs in this direction

**Pull request merged**
